name: Deploy Recipes Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 165.232.166.74
          username: recipes
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/recipes
            git pull origin main
            sudo systemctl restart recipes